version: 2.1
default_workspace: &cdk_workspace
  attach_workspace:
    at: ~/repo

commands:
  setup:
    description: "Install basic dependencies TEST"
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt install python3 python3-pip
      - run: sudo pip3 install --upgrade awscli
      - run: sudo npm install -g esbuild
      - setup_remote_docker:
          version: 20.10.14

orbs:
  enablement: economist-digital-solutions/enablement@1.1.16
  editorial-slack-deployment: economist-digital-solutions/editorial-slack-deployment@0.0.10

jobs:
  cdk-build:
    docker:
      - image: cimg/node:16.13.1
    working_directory: ~/repo
    steps:
      - checkout:
          path: ~/repo
      # Download and cache dependencies
      - restore_cache:
          keys:
            - cdk-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - ~/.npm
          key: -{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths: ['./']


  deploy:
    parameters:
      namespace:
        type: string
        default: ''
    docker:
      - image: cimg/node:16.13.1
    working_directory: ~/repo
    steps:
      - enablement/aws-setup      
      - <<: *cdk_workspace
      - setup
      - run:
          name: Deploy Infrastructure
          environment:
            NAMESPACE: << parameters.namespace >> 
          command: |
            set -e
            bash ./.circleci/deploy.sh

workflows:
  version: 2
  deploy-to-test:
    jobs:
      - cdk-build:
          filters: &filter-test-release
            branches:
              only:
                - 'environment/test'
      - deploy:
          name: deploy-infographics-dev
          namespace: dev
          requires:
            - cdk-build
          context:
            - 'editorial-tools-ctx-circleci'
            - 'editorial-tools-ctx-aws-467992163263'
          filters:
            <<: *filter-test-release

  deploy-to-prod:
    jobs:
      - cdk-build:
          filters: &filter-prod-release
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - deploy:
          requires:
            - cdk-build
          name: 'deploy-infographics-prod'
          context: 
            - 'editorial-tools-ctx-circleci'
            - 'editorial-tools-ctx-aws-993439498522'
          namespace: 'prod'
          filters:
            <<: *filter-prod-release

